export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const INGREDIENTS_ERROR = "INGREDIENTS_ERROR";
