export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSES = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_START';
