export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSES = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_START';
